# Default values for example-app-mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deployment:
  # port exposed in the container
  # this will be used also in the service to route requests to the deployment
  port: 80
  # port name
  portName: http

envs: {}
  # insert here any variable needed by your container
  #MYVAR1: "example"
  # in case you need a variable containing the service name for mongodb 
  # the value must be RELEASE-mongodb
  # where RELEASE is your release name
  #MONGODB_SERVER: "RELEASE-mongodb"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# set resources compatible with a plenus free tier namespace
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 0m
    memory: 0Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mongodb:
  # set resources compatible with a plenus free tier namespace
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 0m
      memory: 0Mi
