apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-app-mongodb.fullname" . }}-envs
  labels:
{{ include "example-app-mongodb.labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.envs }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
